// flow-typed signature: 1fb5e96673790880c57ab9f30fa50424
// flow-typed version: <<STUB>>/@oneblink/cli_v^0.1.4/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oneblink/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oneblink/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oneblink/cli/bin/civicplus' {
  declare module.exports: any;
}

declare module '@oneblink/cli/bin/oneblink' {
  declare module.exports: any;
}

declare module '@oneblink/cli/dist/wrapper' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/apis' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/assume-aws-roles' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/bm-response' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/cors/display' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/cors/read' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/cors/validate' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/deploy' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/handlers' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/network' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/project' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/routes/display' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/routes/get-route-config' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/routes/read' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/routes/validate' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/scope' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/serve' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/teardown' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/types' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/utils/copy-recursive' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/utils/internal' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/utils/project-meta' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/values' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/variables' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/api/wrapper' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/api/deploy' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/api' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/api/info' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/api/scope' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/api/serve' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/api/teardown' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/aws-credentials' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/cli/flags' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/cli/help' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/deploy' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/provision-environment' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/read' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/s3-bucket-factory' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/s3-bucket-params' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/scope' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/show' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/utils/config-helper' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/utils/confirm' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/cdn/lib/write' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/login' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/commands/logout' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/config' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/common/login' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/common/logout' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/constants' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/login-providers/browser' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/login-providers/login-provider-base' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/login-providers/username' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/utils/get-access-token' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/utils/get-jwt' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/utils/get-refresh-token' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/utils/user-config' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/identity/utils/verify-jwt' {
  declare module.exports: any;
}

declare module '@oneblink/cli/lib/oneblink-api-client' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oneblink/cli/bin/civicplus.js' {
  declare module.exports: $Exports<'@oneblink/cli/bin/civicplus'>;
}
declare module '@oneblink/cli/bin/oneblink.js' {
  declare module.exports: $Exports<'@oneblink/cli/bin/oneblink'>;
}
declare module '@oneblink/cli/dist/wrapper.js' {
  declare module.exports: $Exports<'@oneblink/cli/dist/wrapper'>;
}
declare module '@oneblink/cli/lib/api/apis.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/apis'>;
}
declare module '@oneblink/cli/lib/api/assume-aws-roles.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/assume-aws-roles'>;
}
declare module '@oneblink/cli/lib/api/bm-response.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/bm-response'>;
}
declare module '@oneblink/cli/lib/api/cors/display.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/cors/display'>;
}
declare module '@oneblink/cli/lib/api/cors/read.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/cors/read'>;
}
declare module '@oneblink/cli/lib/api/cors/validate.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/cors/validate'>;
}
declare module '@oneblink/cli/lib/api/deploy.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/deploy'>;
}
declare module '@oneblink/cli/lib/api/handlers.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/handlers'>;
}
declare module '@oneblink/cli/lib/api/network.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/network'>;
}
declare module '@oneblink/cli/lib/api/project.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/project'>;
}
declare module '@oneblink/cli/lib/api/routes/display.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/routes/display'>;
}
declare module '@oneblink/cli/lib/api/routes/get-route-config.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/routes/get-route-config'>;
}
declare module '@oneblink/cli/lib/api/routes/read.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/routes/read'>;
}
declare module '@oneblink/cli/lib/api/routes/validate.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/routes/validate'>;
}
declare module '@oneblink/cli/lib/api/scope.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/scope'>;
}
declare module '@oneblink/cli/lib/api/serve.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/serve'>;
}
declare module '@oneblink/cli/lib/api/teardown.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/teardown'>;
}
declare module '@oneblink/cli/lib/api/types.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/types'>;
}
declare module '@oneblink/cli/lib/api/utils/copy-recursive.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/utils/copy-recursive'>;
}
declare module '@oneblink/cli/lib/api/utils/internal.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/utils/internal'>;
}
declare module '@oneblink/cli/lib/api/utils/project-meta.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/utils/project-meta'>;
}
declare module '@oneblink/cli/lib/api/values.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/values'>;
}
declare module '@oneblink/cli/lib/api/variables.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/variables'>;
}
declare module '@oneblink/cli/lib/api/wrapper.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/api/wrapper'>;
}
declare module '@oneblink/cli/lib/commands/api/deploy.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/api/deploy'>;
}
declare module '@oneblink/cli/lib/commands/api/index' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/api'>;
}
declare module '@oneblink/cli/lib/commands/api/index.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/api'>;
}
declare module '@oneblink/cli/lib/commands/api/info.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/api/info'>;
}
declare module '@oneblink/cli/lib/commands/api/scope.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/api/scope'>;
}
declare module '@oneblink/cli/lib/commands/api/serve.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/api/serve'>;
}
declare module '@oneblink/cli/lib/commands/api/teardown.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/api/teardown'>;
}
declare module '@oneblink/cli/lib/commands/cdn/index' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn'>;
}
declare module '@oneblink/cli/lib/commands/cdn/index.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/aws-credentials.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/aws-credentials'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/cli/flags.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/cli/flags'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/cli/help.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/cli/help'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/deploy/index' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/deploy'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/deploy/index.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/deploy'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/provision-environment.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/provision-environment'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/read.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/read'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/s3-bucket-factory.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/s3-bucket-factory'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/s3-bucket-params.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/s3-bucket-params'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/scope/index' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/scope'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/scope/index.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/scope'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/show.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/show'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/utils/config-helper.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/utils/config-helper'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/utils/confirm.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/utils/confirm'>;
}
declare module '@oneblink/cli/lib/commands/cdn/lib/write.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/cdn/lib/write'>;
}
declare module '@oneblink/cli/lib/commands/index' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands'>;
}
declare module '@oneblink/cli/lib/commands/index.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands'>;
}
declare module '@oneblink/cli/lib/commands/login/index' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/login'>;
}
declare module '@oneblink/cli/lib/commands/login/index.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/login'>;
}
declare module '@oneblink/cli/lib/commands/logout/index' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/logout'>;
}
declare module '@oneblink/cli/lib/commands/logout/index.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/commands/logout'>;
}
declare module '@oneblink/cli/lib/config.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/config'>;
}
declare module '@oneblink/cli/lib/identity/common/login.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/common/login'>;
}
declare module '@oneblink/cli/lib/identity/common/logout.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/common/logout'>;
}
declare module '@oneblink/cli/lib/identity/constants.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/constants'>;
}
declare module '@oneblink/cli/lib/identity/index' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity'>;
}
declare module '@oneblink/cli/lib/identity/index.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity'>;
}
declare module '@oneblink/cli/lib/identity/login-providers/browser.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/login-providers/browser'>;
}
declare module '@oneblink/cli/lib/identity/login-providers/login-provider-base.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/login-providers/login-provider-base'>;
}
declare module '@oneblink/cli/lib/identity/login-providers/username.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/login-providers/username'>;
}
declare module '@oneblink/cli/lib/identity/utils/get-access-token.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/utils/get-access-token'>;
}
declare module '@oneblink/cli/lib/identity/utils/get-jwt.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/utils/get-jwt'>;
}
declare module '@oneblink/cli/lib/identity/utils/get-refresh-token.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/utils/get-refresh-token'>;
}
declare module '@oneblink/cli/lib/identity/utils/user-config.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/utils/user-config'>;
}
declare module '@oneblink/cli/lib/identity/utils/verify-jwt.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/identity/utils/verify-jwt'>;
}
declare module '@oneblink/cli/lib/oneblink-api-client.js' {
  declare module.exports: $Exports<'@oneblink/cli/lib/oneblink-api-client'>;
}
