// flow-typed signature: 50a105adbfa204e6da41a967ae1fc029
// flow-typed version: <<STUB>>/@oneblink/sdk_v^0.7.3/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oneblink/sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oneblink/sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oneblink/sdk/classes/Forms' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes/FormsApps' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes/Jobs' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes/Keys' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes/Organisations' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes/TeamMembers' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/form-types' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/forms-app-types' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/aws-sdk_vx.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/axios_v0.19.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/fixpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/jest_v26.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/joi_vx.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/jsonwebtoken_v8.3.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/jwks-rsa_vx.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/uuid_v8.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/types' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/forms-schema' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/forms-validation' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/generate-form-element' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/generate-form-url' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/generate-jwt' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/generate-page-element' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/generate-tenant' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/one-blink-api-error-handler' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/one-blink-api' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/pre-fill-data' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/retrieve-submission-data' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/tenant-configuration' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/verify-jwt' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/tenants/civicplus' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/tenants/oneblink' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oneblink/sdk/classes/Forms.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/Forms'>;
}
declare module '@oneblink/sdk/classes/FormsApps.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/FormsApps'>;
}
declare module '@oneblink/sdk/classes/index' {
  declare module.exports: $Exports<'@oneblink/sdk/classes'>;
}
declare module '@oneblink/sdk/classes/index.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes'>;
}
declare module '@oneblink/sdk/classes/Jobs.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/Jobs'>;
}
declare module '@oneblink/sdk/classes/Keys.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/Keys'>;
}
declare module '@oneblink/sdk/classes/Organisations.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/Organisations'>;
}
declare module '@oneblink/sdk/classes/TeamMembers.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/TeamMembers'>;
}
declare module '@oneblink/sdk/flow-typed/form-types.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/form-types'>;
}
declare module '@oneblink/sdk/flow-typed/forms-app-types.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/forms-app-types'>;
}
declare module '@oneblink/sdk/flow-typed/npm/aws-sdk_vx.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/aws-sdk_vx.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/axios_v0.19.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/axios_v0.19.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/fixpack_vx.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/fixpack_vx.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/jest_v26.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/jest_v26.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/joi_vx.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/joi_vx.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/jsonwebtoken_v8.3.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/jsonwebtoken_v8.3.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/jwks-rsa_vx.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/jwks-rsa_vx.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/prettier_vx.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/uuid_v8.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/uuid_v8.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/types.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/types'>;
}
declare module '@oneblink/sdk/index' {
  declare module.exports: $Exports<'@oneblink/sdk'>;
}
declare module '@oneblink/sdk/index.js' {
  declare module.exports: $Exports<'@oneblink/sdk'>;
}
declare module '@oneblink/sdk/lib/forms-schema.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/forms-schema'>;
}
declare module '@oneblink/sdk/lib/forms-validation.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/forms-validation'>;
}
declare module '@oneblink/sdk/lib/generate-form-element.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/generate-form-element'>;
}
declare module '@oneblink/sdk/lib/generate-form-url.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/generate-form-url'>;
}
declare module '@oneblink/sdk/lib/generate-jwt.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/generate-jwt'>;
}
declare module '@oneblink/sdk/lib/generate-page-element.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/generate-page-element'>;
}
declare module '@oneblink/sdk/lib/generate-tenant.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/generate-tenant'>;
}
declare module '@oneblink/sdk/lib/one-blink-api-error-handler.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/one-blink-api-error-handler'>;
}
declare module '@oneblink/sdk/lib/one-blink-api.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/one-blink-api'>;
}
declare module '@oneblink/sdk/lib/pre-fill-data.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/pre-fill-data'>;
}
declare module '@oneblink/sdk/lib/retrieve-submission-data.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/retrieve-submission-data'>;
}
declare module '@oneblink/sdk/lib/tenant-configuration.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/tenant-configuration'>;
}
declare module '@oneblink/sdk/lib/verify-jwt.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/verify-jwt'>;
}
declare module '@oneblink/sdk/tenants/civicplus.js' {
  declare module.exports: $Exports<'@oneblink/sdk/tenants/civicplus'>;
}
declare module '@oneblink/sdk/tenants/oneblink.js' {
  declare module.exports: $Exports<'@oneblink/sdk/tenants/oneblink'>;
}
